[build]
  base = "finance-app"
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Disable processing for static export
[build.processing]
  skip_processing = true